<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>CableGuard.ControlCenter</AssemblyName>
    <RootNamespace>CableGuard.ControlCenter</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CableGuard.ControlCenter.Core\CableGuard.ControlCenter.Core.csproj" />
  </ItemGroup>

</Project>
