using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CableGuard.ControlCenter.Core.Models;

namespace CableGuard.ControlCenter.Core.Services;

/// <summary>
/// Writes a gitignored runtime pad site YAML for office/test launches.
/// Does not modify algorithm thresholds — only identity + ROI polygon from SAVED Admin Studio profile.
/// </summary>
public static class DetectorRuntimeConfigAdapter
{
    public sealed record PreparedRoi(string SiteConfigPath, string RoiProfileId, string RoiSha256, int PointCount);

    public static PreparedRoi? TryPrepareFallSiteConfig(
        DetectorInstance instance,
        ControlCenterConfig config,
        out string message)
    {
        message = "";
        if (instance.DetectorType != "fall")
        {
            message = "Runtime adapter applies only to fall detectors.";
            return null;
        }

        var templatePath = Path.Combine(config.DetectorRoot, "sites", "zahradky", "horni_pad.yaml");
        if (!File.Exists(templatePath))
        {
            message = $"Template missing: {templatePath}";
            return null;
        }

        var roiId = string.IsNullOrWhiteSpace(instance.RoiProfile) ? "office-fall-test" : instance.RoiProfile;
        var roiPath = RuntimeConfigPaths.RoiFile(config, roiId);
        List<int[]> points;
        int srcW = 0, srcH = 0;
        if (File.Exists(roiPath))
        {
            var profile = RoiProfileService.Load(roiPath);
            if (profile.Points.Count < 3)
            {
                message = $"ROI '{roiId}' has fewer than 3 points (SAVED incomplete).";
                return null;
            }
            points = profile.Points.Select(p => new[] { p.X, p.Y }).ToList();
            srcW = profile.SourceWidth;
            srcH = profile.SourceHeight;
        }
        else
        {
            // Fallback: keep template ROI but still emit office identity for test lab.
            message = $"ROI profile '{roiId}' not found — using template ROI points (SAVED missing).";
            points = new List<int[]>();
        }

        var template = File.ReadAllText(templatePath);
        // Preserve thresholds/weights block from template; rewrite identity + ROI + runtime dirs.
        var outDir = Path.Combine(config.DetectorRoot, "runtime", "config");
        Directory.CreateDirectory(outDir);
        var outPath = Path.Combine(outDir, $"{instance.Id}.site.yaml");

        var roiYaml = points.Count >= 3
            ? string.Join("\n", points.Select(p => $"  - [{p[0]}, {p[1]}]"))
            : ExtractRoiBlock(template);

        var eventsDir = $"runtime/office/{instance.Id}/events";
        var snapsDir = $"runtime/office/{instance.Id}/snapshots";
        Directory.CreateDirectory(Path.Combine(config.DetectorRoot, eventsDir.Replace('/', Path.DirectorySeparatorChar)));
        Directory.CreateDirectory(Path.Combine(config.DetectorRoot, snapsDir.Replace('/', Path.DirectorySeparatorChar)));

        var yaml = $"""
            # GENERATED by Admin Studio DetectorRuntimeConfigAdapter — do not commit.
            # Algorithm thresholds/weights copied from sites/zahradky/horni_pad.yaml (unchanged).
            # ROI from Admin Studio profile '{roiId}' (activation_state=saved).

            site_id: office
            station_id: office-test
            service_id: {instance.Id}
            camera_id: {instance.InputStream}

            model:
              logical_name: zahradky-shared-yolo11m-pose
              path: models/shared/yolo11m-pose.pt
              imgsz: 480
              process_every_n: 1
              tracker: botsort.yaml
              classes: [0]

            roi_points:
            {roiYaml}

            {ExtractSection(template, "thresholds:")}
            {ExtractSection(template, "risk_weights:")}

            runtime:
              snapshots_dir: {snapsDir}
              events_dir: {eventsDir}
              history_maxlen: 5

            publishers:
              jsonl:
                enabled: true
              telegram:
                enabled_env: TELEGRAM_ENABLED
              event_core:
                enabled: {instance.PublishEventCore.ToString().ToLowerInvariant()}
                note: Overridden at runtime by CABLEGUARD_EVENT_CORE_EVENTS; office test sets true + test_mode.

            # metadata for logs
            admin_studio_roi_profile: {roiId}
            admin_studio_source_width: {srcW}
            admin_studio_source_height: {srcH}
            """;

        File.WriteAllText(outPath, yaml);
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(roiYaml))).ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(message))
            message = $"Prepared site config for {instance.Id} with ROI '{roiId}' ({points.Count} pts).";
        return new PreparedRoi(outPath, roiId, hash[..16], points.Count >= 3 ? points.Count : -1);
    }

    private static string ExtractRoiBlock(string template)
    {
        var lines = template.Split('\n');
        var collecting = false;
        var buf = new List<string>();
        foreach (var line in lines)
        {
            if (line.StartsWith("roi_points:", StringComparison.Ordinal))
            {
                collecting = true;
                continue;
            }
            if (collecting)
            {
                if (line.Length > 0 && !char.IsWhiteSpace(line[0]) && !line.StartsWith('#'))
                    break;
                if (line.TrimStart().StartsWith('-'))
                    buf.Add(line.TrimEnd('\r'));
            }
        }
        return string.Join("\n", buf);
    }

    private static string ExtractSection(string template, string header)
    {
        var lines = template.Replace("\r\n", "\n").Split('\n');
        var start = Array.FindIndex(lines, l => l.StartsWith(header, StringComparison.Ordinal));
        if (start < 0) return header + "\n";
        var buf = new List<string> { lines[start] };
        for (var i = start + 1; i < lines.Length; i++)
        {
            if (lines[i].Length > 0 && !char.IsWhiteSpace(lines[i][0]) && !lines[i].StartsWith('#'))
                break;
            buf.Add(lines[i]);
        }
        return string.Join("\n", buf).TrimEnd();
    }
}
