$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$DeployDir = Join-Path $Root "deploy\mediamtx"
$LegacyConfig = Join-Path $env:USERPROFILE "Documents\mediamtx\mediamtx.yml"
$LocalConfig = Join-Path $DeployDir "mediamtx.local.yml"
$ExampleConfig = Join-Path $DeployDir "mediamtx.example.yml"

if (-not (Test-Path $LegacyConfig)) {
    Write-Host "Legacy config not found at $LegacyConfig" -ForegroundColor Yellow
    Write-Host "Copy mediamtx.example.yml to mediamtx.local.yml manually." -ForegroundColor Yellow
    exit 1
}

$content = Get-Content $LegacyConfig -Raw
$match = [regex]::Match($content, '(?ms)^\s*kamera4:\s*\r?\n\s*source:\s*(.+)$')
if (-not $match.Success) {
    Write-Host "Could not find legacy path kamera4 source in legacy config." -ForegroundColor Red
    exit 1
}
$source = ($match.Groups[1].Value.Trim() -split "`r?`n")[0]

$template = @"
###############################################
# LOCAL ONLY – generated by setup_mediamtx_local_config.ps1
# DO NOT COMMIT
###############################################

logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: 127.0.0.1:9997

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp]

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcAllowOrigin: "*"

hls: yes
hlsAddress: :8888

playback: no

paths:
  zahradky-horni-stanice:
    source: $source
    rtspTransport: tcp
    sourceOnDemand: no
"@

Set-Content -Path $LocalConfig -Value $template -Encoding UTF8
Write-Host "Created local config: $LocalConfig" -ForegroundColor Green
Write-Host "RTSP source copied from legacy path kamera4 (value not printed)." -ForegroundColor Green
